class RecentFile {
  final int assetID;
  final String assetName, productType, quantity, optionEdit, optionDelete;

  RecentFile(
      {this.assetID,
      this.assetName,
      this.productType,
      this.quantity,
      this.optionEdit,
      this.optionDelete});
}

List demoRecentFiles = [
  // RecentFile(
  //   icon: "assets/icons/xd_file.svg",
  //   title: "XD File",
  //   date: "01-03-2021",
  //   size: "3.5mb",
  //   test: "XD File",
  // ),
  // RecentFile(
  //   icon: "assets/icons/Figma_file.svg",
  //   title: "Figma File",
  //   date: "27-02-2021",
  //   size: "19.0mb",
  //   test: "XD File",
  // ),
  // RecentFile(
  //   icon: "assets/icons/doc_file.svg",
  //   title: "Documetns",
  //   date: "23-02-2021",
  //   size: "32.5mb",
  //   test: "XD File",
  // ),
  // RecentFile(
  //   icon: "assets/icons/sound_file.svg",
  //   title: "Sound File",
  //   date: "21-02-2021",
  //   size: "3.5mb",
  //   test: "XD File",
  // ),
  // RecentFile(
  //   icon: "assets/icons/media_file.svg",
  //   title: "Media File",
  //   date: "23-02-2021",
  //   size: "2.5gb",
  //   test: "XD File",
  // ),
  // RecentFile(
  //   icon: "assets/icons/pdf_file.svg",
  //   title: "Sals PDF",
  //   date: "25-02-2021",
  //   size: "3.5mb",
  //   test: "XD File",
  // ),
  // RecentFile(
  //   icon: "assets/icons/excle_file.svg",
  //   title: "Excel File",
  //   date: "25-02-2021",
  //   size: "34.5mb",
  //   test: "XD File",
  // ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
  RecentFile(
    assetID: 123456,
    assetName: "Macbook Pro",
    productType: "Laptop",
    quantity: "20",
    optionEdit: "assets/iconsv1/edit.svg",
    optionDelete: "assets/iconsv1/delete.svg",
  ),
];
